baseURL = 'https://nanjingning.com/'
defaultContentLanguage = 'zh'
languageCode = 'zh-Hant'
title = '南京的那個寧'
theme = 'dream'
hasCJKLanguage = true

[params]
author = '南京的那個寧'
description = '探索南京的美麗與文化，分享攝影、旅行、美食和生活感悟。關注我們，感受生命的詩意與溫暖。'
avatar = '/images/avatar.jpg'
images = ['/images/avatar.jpg']

showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true

[services]
[services.googleAnalytics]
ID = 'G-80XRCBNSTD'

[caches]
[caches.images]
dir = ':cacheDir/images'
